In [1]:
# Numpy is an library which is used in python for dat computing.
#here we use "np as a alias of numpy"

import numpy as np

In [2]:
l1=[1,2,3,4]  # this is an example of single dimentinal array.

In [5]:
n1=np.array(l1)

n1


In [6]:
n1


array([1, 2, 3, 4])

In [7]:
# Multidimentional Array.

In [9]:
n2=np.array([[1,2,3,4],[4,4,6,7]])

In [10]:
n2

array([[1, 2, 3, 4],
       [4, 4, 6, 7]])

In [11]:
type(n2)

numpy.ndarray

In [12]:
# Initialize Numpy array with Zeros for that "zeros"method will we used

In [14]:
n1=np.zeros((1,2)) # it is 1*2 array means 1 row and 2 column

In [15]:
n1

array([[0., 0.]])

In [16]:
n1=np.zeros((5,5)) # it  display the array initialize with "0" with 5*5 that 5 row and 5 column

In [17]:
n1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
# initialize with same number for that "full" method will be used

In [23]:
n1=np.full((7,7),10)

In [24]:
n1

array([[10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10]])

In [25]:
#Initialize the numpy array within a range for that "arange" methid will be used

In [26]:
n1=np.arange(10,20)

In [27]:
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [28]:
# if you want to find the array in a range with some difference you can also do this

In [29]:
n1=np.arange(10,40,5)

In [30]:
n1

array([10, 15, 20, 25, 30, 35])

In [31]:
#initialize the numpy with random number for that we have to use "random submodule" and the inbuit function of this moduke is "randint" whic we have to use

In [36]:
n1=np.random.randint(1,100,5)

In [39]:
n1

array([30, 74, 58, 74, 81])

In [41]:
# checking the shape of numpy array and changing the shape of numpy array

In [44]:
n1=np.array([[1,2,3],[4,5,6]])

In [45]:
n1

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
n1.shape # display the shape of numpy array

(2, 3)

In [47]:
# how to change the shaoe if numpy array

In [49]:
n1.shape=(3,2)

n1.shape 

In [50]:
n1.shape

(3, 2)

In [53]:
n1 # oytput after changing  the shape of array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [54]:
#how to joining the numpy array
#1.vstack() 2.hstack() 3.column_stack()


In [61]:
n1=np.array([1,2,3,4])
n2=np.array([4,5,6,5])

In [62]:
np.vstack((n1,n2)) # "vstack()" join the  two or more array in vertical vise

array([[1, 2, 3, 4],
       [4, 5, 6, 5]])

In [64]:
np.hstack((n1,n2)) #"hstck()" join the  two or more array in horizonatl wisw

array([1, 2, 3, 4, 4, 5, 6, 5])

In [65]:
np.column_stack((n1,n2)) #"column_stack" join  the two or more array in column wise 

array([[1, 4],
       [2, 5],
       [3, 6],
       [4, 5]])

In [66]:
# intersection and difference 
#for intersection"intersect1d() methid is used
#for difference "setdiff1d()" method is used

In [68]:
n1=np.array([10,20,30,40,50,60])
n2=np.array([10,30,70,50])

In [69]:
np.intersect1d(n1,n2)

array([10, 30, 50])

In [70]:
np.setdiff1d(n1,n2)

array([20, 40, 60])

In [71]:
np.setdiff1d(n2,n1)

array([70])

In [74]:
# Adition of numpy array "sum()" method is used

In [75]:
n1=np.array([10,20])
n2=np.array([40,60])

In [77]:
np.sum([n1,n2]) # this method add all the value of both the array

130

In [80]:
np.sum([n1,n2],axis=0) # add the array value with respect to column

array([50, 80])

In [81]:
np.sum([n1,n2],axis=1) # add the array with respect to rows

array([ 30, 100])

In [83]:
# numpy array mathematics
#1basi addition
#2.basic subtraction
#3.basic multiplication
#4.basic division

In [84]:
n1=np.array([10,20,30]) 
n1=n1+5 # add 5 to avery value in array

In [85]:
n1

array([15, 25, 35])

In [86]:
n1=n1-5  # subtract 5 from every value

In [87]:
n1

array([10, 20, 30])

In [88]:
n1=n1*3 #muliply every number with 3

In [89]:
n1

array([30, 60, 90])

In [92]:
n1=n1/2 # diide every number with 2

In [91]:
n1

array([15., 30., 45.])

In [95]:
#statistic operation like mean,medin and standard devialtion
#mean()
#median()
#std()

In [96]:
n1=np.array([10,20,30,40,50,60])

In [99]:
np.mean(n1)

35.0

In [101]:
np.median(n1)

35.0

In [102]:
np.std(n1)

17.07825127659933

In [103]:
#numpy save and load
#save('my_numpy',n1)
#load('my_numpy.npy')

In [105]:
n1=np.array([10,20,30,40,50])
np.save('my_numpy',n1)

In [106]:
n2=np.load('my_numpy.npy')

In [107]:
n2

array([10, 20, 30, 40, 50])