In [1]:
# program to add the two array using numpy array

In [2]:
import numpy as np

In [3]:
n1=np.array([10,20])

In [4]:
n2=np.array([30,40])

In [5]:
np.sum([n1,n2])

100

In [6]:
#program to sum in column wise:axis=0

In [8]:
np.sum([n1,n2],axis=0)

array([40, 60])

In [10]:
np.sum([n1,n2],axis=1)

array([30, 70])

In [12]:
# ----basic addition----adding x to every vlue

In [14]:
n1=np.array([10,20,30])

In [15]:
n1=n1+1

In [16]:
n1

array([11, 21, 31])

In [17]:
# subratct x from every value

In [18]:
n1=n1-1

In [19]:
n1

array([10, 20, 30])

In [20]:
# multiply every value with x

In [21]:
n1=n1*3

In [22]:
n1

array([30, 60, 90])

In [23]:
# divide every value with x

In [24]:
n1=n1/2

In [25]:
n1

array([15., 30., 45.])

In [26]:
#---- find mean,median and standard deviation:

In [31]:
n1=np.array([1,2,3,4,5,6,7,8])

In [32]:
np.median(n1)

4.5

In [33]:
np.mean(n1)

4.5

In [34]:
np.std(n1)

2.29128784747792